[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
    ## {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope | trim_start_matches(pat="(") | trim_end_matches(pat=")") }}:** {% endif %}\
            {% if commit.breaking %}**BREAKING** {% endif %}\
            {{ commit.message | upper_first }}\
            {% if commit.remote.pr_number %} ([#{{ commit.remote.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ commit.remote.pr_number }})){% endif %}\
            ([`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))\
    {% endfor %}
{% endfor %}\n
"""
trim = true
footer = ""

[commit_parser]
filter_unconventional = true
split_commits = false
group_pattern = "^(?<group>[^:]+)"

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
    { message = "^feat", group = "Features", default = true },
    { message = "^fix", group = "Bug Fixes", default = true },
    { message = "^doc", group = "Documentation", default = true },
    { message = "^perf", group = "Performance", default = true },
    { message = "^refactor", group = "Refactor", default = true },
    { message = "^style", group = "Styling", default = true },
    { message = "^test", group = "Testing", default = true },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^chore\\(npm\\)|^chore\\(bump\\)", skip = true },
    { message = "^ci", group = "CI/CD", default = true },
    { message = "^build", group = "Build", default = true },
    { body = ".*Security", group = "Security", default = true },
]
protect_breaking_commits = true
filter_commits = false
tag_pattern = "v[0-9].*"
